### ISSUE TITLE
No longer works in Fx47

### ISSUE THREAD

**Issue by yfdyh000** [wesley-chen/imagepicker#1]
See the https://bugzilla.mozilla.org/show_bug.cgi?id=1248385.

**Comment by eight04** [comment]
For those who need this addon in Aurora, comment out these lines: https://github.com/wesley-chen/imagepicker/blob/master/srcExtension/chrome/content/ipOverlay.js#L11-L23

**Comment by wesley-chen** [comment]
Thanks All! Please try the Image Picker v1.9.4 here: https://addons.mozilla.org/firefox/addon/image-picker/versions/
