### ISSUE TITLE
toValidName doesn't escape "\"

### ISSUE THREAD

**Issue by eight04** [wesley-chen/imagepicker#3]
https://github.com/wesley-chen/imagepicker/blob/d5dfc8cf5fa8ecbc9554293773b9f69b5aee2372/srcExtension/modules/fileUtils.js#L93
Need 4 backslashes.
```
        var reg = new RegExp("[\\\\/:*?\"<>|]", "g");
```

**Comment by wesley-chen** [comment]
Thanks for the fixing. I have tested and merged your chagne.
